#define SECRET_SSID "Internett"		
#define SECRET_PASS "Interniet"	

#define SECRET_CH_ID_AIRHEATER 1219031
#define SECRET_CH_ID_CONTROLLER 1220602	          	

#define SECRET_WRITE_APIKEY_AIRHEATER "LU87QEE8DRHOEB92"
#define SECRET_READ_APIKEY_AIRHEATER "0A6UBGHH9FEAUM37"

#define SECRET_WRITE_APIKEY_CONTROLLER "E43LJ2EEYBS1BZKN"
#define SECRET_READ_APIKEY_CONTROLLER "TRZXIZ9LKGHPHBOR"